# Generated by Django 4.1.6 on 2023-02-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proffesion',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
