# Generated by Django 4.1.6 on 2023-02-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0003_alter_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
