# Generated by Django 4.1.6 on 2023-02-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0005_product_added_alter_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
