# Generated by Django 4.1.6 on 2023-02-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0007_type_of_product_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='type_of_product',
        ),
    ]
