# Generated by Django 4.1.6 on 2023-02-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0008_alter_product_type_delete_type_of_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_of_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StoreApp.type_of_product'),
        ),
    ]
